pythontask/urls.py
from django.contrib import admin
from django.urls import path
from task import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.loginuser,name='loginuser'),
    path('signup/',views.signupuser,name='signupuser'),
    path('profile/',views.userprofile,name='userprofile'),
    path('logout/',views.logoutuser,name='logoutuser'),
    path('viewuser/<int:emp_pk>',views.viewuserprofile,name='viewuserprofile'),
    path('edituser/<int:emp_pk>',views.edituserprofile,name='edituserprofile'),
    path('create/',views.createprofile,name='createprofile'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

task/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
# Create your models here.

class Employees(models.Model):
    firstName = models.CharField(max_length=30,null=True)
    middleName = models.CharField(max_length=30,null=False)
    lastName = models.CharField(max_length=30,null=True)
    email = models.EmailField(max_length=50,null=False)
    phone = PhoneNumberField(null=True)
    DOB = models.DateField(null=False)

    def __str__(self):
        return self.firstName
    
class EmployeeTable(models.Model):
    firstName = models.CharField(max_length=30)
    lastName = models.CharField(max_length=30)
    email = models.EmailField(max_length=50)
    phone = PhoneNumberField()
    DOB = models.DateField()


    def __str__(self):
        return self.firstName


class EmployeesTable(models.Model):
    firstName = models.CharField(max_length=30)
    lastName = models.CharField(max_length=30)
    email = models.EmailField(max_length=50)
    phone = PhoneNumberField()
    DOB = models.DateField()
    img = models.ImageField(upload_to='images/%Y/%m/%d/',default='default.jpg')
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.firstName

task/forms.py
from django import forms
from .models import EmployeesTable

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = EmployeesTable
        fields=['firstName','lastName','email','phone','DOB','img']

task/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login,logout,authenticate
from .forms import EmployeeForm
from .models import EmployeesTable
from .passwords import Special
from django.contrib.auth.decorators import login_required
# Create your views here.

def signupuser(request):
    if request.method == 'GET':
        return render(request,'task/signup2.html',{'form':UserCreationForm()})
    else:
        sp = Special(request.POST['password1'])
        #errors
        err1 = "Password too short"
        err2 = "Password can not be Entirely Numeric"
        err3 = "Password must contain a small letter"
        err4 = "Password must have at least one numeric"
        err5 = "Password must have at least one special character from these [_@$/|?#]"
        err6 = "Password must have at least one Capital Letter"
        
        if len(request.POST['password1']) <= 7:
            return render(request,'task/signup2.html',{'form':UserCreationForm(),"error":err1})
        elif request.POST['password1'].isdigit():
            return render(request,'task/signup2.html',{'form':UserCreationForm(),"error":err2})
        elif sp.capitalCheck() == False:
            return render(request,'task/signup2.html',{'form':UserCreationForm(),"error":err6})
        elif sp.smallCheck()==False:
            return render(request,'task/signup2.html',{'form':UserCreationForm(),"error":err3})
        elif sp.numCheck() == False:
            return render(request,'task/signup2.html',{'form':UserCreationForm(),"error":err4})
        elif sp.checkSpecial() == False:
            return render(request,'task/signup2.html',{'form':UserCreationForm(),"error":err5})
        elif request.POST['password1'] == request.POST['password2']:
            try:
                user=User.objects.create_user(username=request.POST['username'],password=request.POST['password1'])
                user.save()
                login(request,user)
                return redirect('userprofile')
            except IntegrityError:
                return render(request,'task/signup2.html',{'form':UserCreationForm(),"error":"User Name Taken Already."})
            except Exception as e:
                return render(request,'task/signup2.html',{'form':UserCreationForm(),"error":e})

def loginuser(request):
    if request.method == 'GET':
        return render(request,'task/login2.html',{'form':AuthenticationForm()})
    else:
        user = authenticate(request,username=request.POST['username'],password=request.POST['password'])
        if user is None:
            errmsg = "Username & password does not match."
            return render(request,'task/login2.html',{'form':AuthenticationForm(),'error':errmsg})
        else:
            try:
                login(request,user)
                return redirect('userprofile')
            except Exception as e:
                return render(request,'task/login2.html',{'form':AuthenticationForm(),'error':e})

def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('loginuser')

@login_required
def userprofile(request):
    emp_det = EmployeesTable.objects.filter(user=request.user)
    # profile = User.objects.get(id=request.user.id)
    # emp_pk = profile
    # obj = get_object_or_404(EmployeesTable,user=profile)
    return render(request,'task/profile.html',{'obj':emp_det})

@login_required
def createprofile(request):
    if request.method == 'GET':
        return render(request,'task/createprofile2.html',{'form':EmployeeForm()})
    else:
        try:
            form = EmployeeForm(request.POST,request.FILES)
            newEmployee = form.save(commit=False)
            newEmployee.user = request.user
            newEmployee.save()
            return redirect('userprofile')
        except ValueError:
            return render(request,'task/createprofile2.html',{'form':EmployeeForm(),'error':"Bad Data"})

        except Exception as e:
            return render(request,'task/createprofile2.html',{'form':EmployeeForm(),'error':e})

@login_required
def viewuserprofile(request,emp_pk):
    emp = get_object_or_404(EmployeesTable,pk=emp_pk,user=request.user)
    if request.method == 'GET':
        return render(request,'task/viewuserprofile.html',{'emp':emp})
    else:
        emp.delete()
        return redirect('userprofile')

@login_required
def edituserprofile(request,emp_pk):
    emp = get_object_or_404(EmployeesTable,pk=emp_pk,user=request.user)
    if request.method == 'GET':
        return render(request,'task/editprofile2.html',{'form':EmployeeForm(instance=emp),'emp':emp})
    else:
        try:
            form = EmployeeForm(request.POST,request.FILES,instance=emp)
            form.save()
            return redirect('userprofile')
        except ValueError:
            return render(request,'task/editprofile2.html',{'form':EmployeeForm(instance=emp),'emp':emp,'error':'Bad Data'})
        except Exception as e:
            return render(request,'task/editprofile2.html',{'form':EmployeeForm(instance=emp),'emp':emp,'error':e})

task/templates/task/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'task/style.css' %}">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <title>Python Task</title>
    </head>
    <body>
        {% if user.is_authenticated %}
        <div class="topnav">
            <h3 class="logednm">Logged In as {{ user.username }}</h3>
            <a href="{% url 'createprofile' %}">Create Profile</a>
            <a href="{% url 'userprofile' %}">User Profile</a>
            <a href="#" onclick="$('#signOutBtn').click()">Logout</a>
        </div>
        <form  method="POST" style='display: none;' action="{% url 'logoutuser' %}">
            {%csrf_token %}
            <!-- <input type="submit" id="logout" value="Logout" /> -->
            <button type="submit" id="signOutBtn" class="btn btn-danger">Log Out</button>
        </form>
        {% else %}
        <div class ="topnav">
            <a href="{% url 'signupuser' %}">Signup</a>
            <a href="{% url 'loginuser' %}">Login</a>
        </div>
        {% endif %}
        {% block content %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    </body>
</html>

task/templates/task/createprofile.html
{% extends "task/base.html"%}

{% block content %}

<h3>Enter The Below Credentials: </h3>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save"/>
</form>
{% endblock %}

task/templates/task/createprofile2.html
{% extends "task/base.html"%}
{% block content %}

<h3 style="color:#800000;">Enter The Below Credentials: </h3>

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
        {% endif %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="id_firstName">FirstName:</label><br>
            <input type="text"  placeholder="First Name" name="firstName" maxlength="30" required="" id="id_firstName"><br><br>

            <label for="id_lastName">LastName:</label><br>
            <input type="text" placeholder="Last Name" name="lastName" maxlength="30" required="" id="id_lastName"><br><br>

            <label for="id_email">Email:</label><br>
            <input type="email" placeholder="Email ID" name="email" maxlength="50" required="" id="id_email"><br><br>

            <label for="id_phone">Phone:</label><br>
            <input type="tel" placeholder="eg:+91 10 digit number" name="phone" maxlength="128" required="" id="id_phone"><br><br>

            <label for="id_DOB">DOB:</label><br>
            <input type="date" name="DOB" required="" id="id_DOB"><br><br>

            <label for="id_img">Image:</label><br>
            <input type="file" name="img" accept="image/*" id="id_img"><br><br>

            <input type="submit" class="btn btn-outline-danger" value="Save" />
        </form>
    </div>
</div>


{% endblock %}

task/templates/task/editprofile.html
{% extends "task/base.html"%}

{% block content %}


<div class="alert alert-danger" role="alert">
    {{error}}
</div>



<form method ="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update"/>
</form>


{% endblock %}

task/templates/task/editprofile2.html
{% extends "task/base.html"%}
{% block content %}

<h3 style="color:#800000;">Enter The Below Credentials: </h3>

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
        {% endif %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="id_firstName">FirstName:</label><br>
            <input type="text" value="{{emp.firstName}}" placeholder="First Name" name="firstName" maxlength="30" required="" id="id_firstName"><br><br>

            <label for="id_lastName">LastName:</label><br>
            <input type="text" value="{{emp.lastName}}" placeholder="Last Name" name="lastName" maxlength="30" required="" id="id_lastName"><br><br>

            <label for="id_email">Email:</label><br>
            <input type="email" value="{{emp.email}}" placeholder="Email ID" name="email" maxlength="50" required="" id="id_email"><br><br>

            <label for="id_phone">Phone:</label><br>
            <input type="tel" value="{{emp.phone}}" placeholder="eg:+91 10 digit number" name="phone" maxlength="128" required="" id="id_phone"><br><br>

            <label for="id_DOB">DOB:</label><br>
            <input type="date" value="{{emp.DOB}}" name="DOB"  id="id_DOB"><br><br>

            <label for="id_img">Image:</label><br>
            <input type="file" value="{{emp.img.url}}" name="img" accept="image/*" id="id_img"><br><br>

            <input type="submit" class="btn btn-outline-danger" value="Update" />
        </form>
    </div>
</div>


{% endblock %}

task/templates/task/login2.html
{% extends "task/base.html"%}
{% block content %}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>

<div class="form">
    <h2 style="color:#800000;">LogIn</h2>
    <form method="POST">

        {% csrf_token %}
        <label for="username">Username</label><br>
        <input type="text" name="username" id="username" autocomplete="off" placeholder="Enter Username" /><br><br>

        <label for="password">Password</label><br>
        <input type="password" name="password" id="password" placeholder="Enter Password" /><br><br>

        <input type="submit" class="btn btn-outline-danger" value="Login" /><br><br>

        <p>Does not have an account <a style="color:#800000;" href="{% url 'signupuser' %}">Signup</a></p>

    </form>

</div>



{% endblock %}

task/templates/task/profile.html
{% extends "task/base.html"%}

{% block content %}

{% if obj %}
<h3>Total no of Employees: {{ obj.count }} </h3>
<br>
<br>
{% for ob in obj %}
<h2>
<ul>
<li>{{ob.firstName}} {{ob.lastName}} <a style="color:#800000;"  href="{% url 'viewuserprofile' ob.id %}">View Profile</a> <a style="color: #800000;" href="{% url 'edituserprofile' ob.id %}">Edit Profile</a> </li>
</ul>
</h2>
{% endfor %}
{% else %}
<h2>No Employess has been adde <a href="{% url 'createprofile' %}">add employees</a></h2>
{% endif %}



{% endblock %}

task/templates/task/signup2.html
{% extends "task/base.html"%}

{% block content %}

<div class="alert alert-danger" role="alert">
    {{error}}
</div>

<div class="form2">
    <h2 style="color:#800000;">Sign Up</h2>
    <form method="POST">
        {% csrf_token %}
        <label for="username">Username</label><br>
        <input type="text" autocomplete="off" name="username" id="username" placeholder="Enter Username"aria-describedby="usernameHelp"><br><br>

        <label for="password1">Password</label><br>
        <input type="password" name="password1" id="password1" placeholder="Enter Password" /><br><br>

        <label for="password2">Confirm Password</label><br>
        <input type="password" name="password2" id="password2" placeholder="Enter Password Again" /><br><br>

        <input type="submit" class="btn btn-outline-danger" value="Sign Up" /><br><br>

        <p>Have an account <a style="color:#800000;" href="{% url 'loginuser' %}">Login</a></p>
    </form>


</div>


{% endblock %}

task/templates/task/viewuserprofile.html
{% extends "task/base.html"%}

{% block content %}
<h2>{{emp.firstName}}'s profile</h2>
<img src="{{ emp.img.url }}" class="img-responsive" style="width: 10%; float: left; margin-right: 10px;" />
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="profcolor">
    <ul>
        <li>Employee ID : {{emp.id}}</li>
        <li>Employee Name : {{emp.firstName}} {{emp.lastName}}</li>
        <li>Employee Email : {{emp.email}}</li>
        <li>Employee Contact : {{emp.phone}}</li>
        <li>Employee DOB : {{emp.DOB}}</li>
    </ul>
</div>
<a href="#" class="btn btn-danger" onclick="$('#delete').click()">Delete Profile</a> 
<form method="POST" style='display: none;' action="{% url 'viewuserprofile' emp.id %}">
    {% csrf_token %}
    <input id="delete" type="submit" value="Delete Todo" />
</form>

{% endblock %}